---
- hosts: devservers

  tasks:
    - name: create file under /tmp
      file:
        path: /tmp/hey.txt
        state: touch
      notify:
        - display a word
        
    - name: reboot remote host
      shell: reboot

  handlers:
    - name: display a word
      shell: echo "file has been deleted" >> /tmp/my_file   
